services:
  db:
    image: postgres:alpine3.19
    restart: always
    environment:
      POSTGRES_PASSWORD: "goguldrivepgroot"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgdata:
